version: "3"
########################
# Time Series Collector
# ######################
#
services:
 influxdb:
  build:
   context: ./influxdb
   dockerfile: Dockerfile
  container_name: cl-influxdb
  ports:
   - "8083:8083"
   - "8086:8086"
   - "8090:8090"
  env_file:
   - 'influxdb/env.influxdb'
  volumes:
   #Data Persistency
   # sudo mkdir -p /home/techx/containers/svr/docker/influxdb/data
   - /home/techx/containers/svr/docker/influxdb/data:/var/lib/influxdb

 grafana:  
  build:
   context: ./grafana
   dockerfile: Dockerfile
  container_name: cl-grafana
  ports:
   - "3000:3000"
  env_file:
   - 'grafana/env.grafana'
  links:
   - influxdb
  volumes:
   #Data Persistency
   # sudo mkdir -p /home/techx/containers/svr/docker/grafana/data ; chown 472:472 
   - /home/techx/containers/svr/docker/grafana/data:/var/lib/grafana


 nginx:
  build:
   context: ./nginx
   dockerfile: Dockerfile
  container_name: cl-nginx
  ports:
   - "80:80"
  links:
   - grafana
  volumes:
   #Data Persistency
   - /home/techx/containers/cltelemetry/nginx/nginx.conf:/etc/nginx/nginx.conf

 
